//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ImageTool.rc
//
#define IDD_FILE_NEW                    9
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDR_MAINFRAME                   128
#define IDR_ImageToolTYPE               129
#define IDD_BRIGHTNESS                  130
#define IDR_AVI_TYPE                    130
#define IDR_AVI_PLAY                    130
#define IDD_CONTRAST                    131
#define IDD_HISTOGRAM                   132
#define IDD_GAMMA_CORRECTION            133
#define IDD_ARITHMETIC                  134
#define IDD_GAUSSIAN                    135
#define IDD_ADD_NOISE                   136
#define IDD_DIFFUSION                   137
#define IDD_TRANSLATE                   138
#define IDD_RESIZE                      139
#define IDD_ROTATE                      140
#define IDD_FREQUENCY_FILTERING         141
#define IDD_HARRIS                      142
#define IDD_COLOR_COMBINE               143
#define IDD_BINARIZATION                144
#define IDD_FOURIER_DESCRIPTOR          145
#define IDC_WIDTH                       1001
#define IDC_HEIGHT                      1002
#define IDC_IMAGETYPE                   1003
#define IDC_BRIGHTNESS_SLIDER           1004
#define IDC_BRIGHTNESS_EDIT             1005
#define IDC_CONTRAST_SLIDER             1006
#define IDC_CONTRAST_EDIT               1007
#define IDC_GAMMA_SLIDER                1008
#define IDC_GAMMA_EDIT                  1009
#define IDC_COMBO_IMAGE1                1010
#define IDC_COMBO_IMAGE2                1011
#define IDC_FUNCTION1                   1012
#define IDC_FUNCTION2                   1013
#define IDC_FUNCTION3                   1014
#define IDC_FUNCTION4                   1015
#define IDC_FUNCTION5                   1016
#define IDC_FUNCTION6                   1017
#define IDC_SIGMA_EDIT                  1018
#define IDC_SIGMA_SLIDER                1019
#define IDC_NOISE_RADIO1                1020
#define IDC_NOISE_RADIO2                1021
#define IDC_NOISE_AMOUNT                1022
#define IDC_DIFFUSION_LAMBDA            1023
#define IDC_DIFFUSION_K                 1024
#define IDC_DIFFUSION_ITER              1025
#define IDC_NEW_SX                      1026
#define IDC_NEW_SY                      1027
#define IDC_OLD_WIDTH                   1028
#define IDC_NEW_WIDTH                   1029
#define IDC_SPIN_WIDTH                  1030
#define IDC_OLD_HEIGHT                  1031
#define IDC_NEW_HEIGHT                  1032
#define IDC_SPIN_HEIGHT                 1033
#define IDC_ASPECT_RATIO                1034
#define IDC_IMAGE_WND                   1034
#define IDC_INTERPOLATION               1035
#define IDC_ROTATE1                     1036
#define IDC_ROTATE2                     1037
#define IDC_ROTATE3                     1038
#define IDC_ROTATE4                     1039
#define IDC_ANGLE                       1040
#define IDC_FILTER_TYPE                 1041
#define IDC_FILTER_SHAPE                1042
#define IDC_CUTOFF_FREQ                 1043
#define IDC_CUTOFF_RANGE                1044
#define IDC_THRESHOLD                   1045
#define IDC_COLOR_SPACE                 1046
#define IDC_COMBO_IMAGE3                1047
#define IDC_THRESHOLD_SLIDER            1049
#define IDC_THRESHOLD_EDIT              1050
#define IDC_PERCENT                     1051
#define ID_WINDOW_DUPLICATE             32771
#define ID_VIEW_ZOOM1                   32772
#define ID_VIEW_ZOOM2                   32773
#define ID_VIEW_ZOOM3                   32774
#define ID_VIEW_ZOOM4                   32775
#define ID_IMAGE_INVERSE                32776
#define ID_IMAGE_BRIGHTNESS             32777
#define ID_IMAGE_CONTRAST               32778
#define ID_HISTO_EQUALIZE               32779
#define ID_VIEW_HISTOGRAM               32780
#define ID_GAMMA_CORRECTION             32781
#define ID_IMAGE_ARITHMETIC             32782
#define ID_BITPLANE_SLICING             32783
#define ID_WINDOW_CLOSEALL              32784
#define ID_FILTER_MEAN                  32785
#define ID_FILTER_WEIGHTED_MEAN         32786
#define ID_FILTER_GAUSSIAN              32787
#define ID_FILTER_LAPLACIAN             32788
#define ID_FILTER_UNSHARP_MASK          32789
#define ID_ADD_NOISE                    32790
#define ID_FILTER_MEDIAN                32791
#define ID_FILTER_DIFFUSION             32792
#define ID_IMAGE_TRANSLATION            32793
#define ID_IMAGE_RESIZE                 32794
#define ID_IMAGE_ROTATE                 32795
#define ID_IMAGE_MIRROR                 32796
#define ID_IMAGE_FLIP                   32797
#define ID_FOURIER_DFT                  32798
#define ID_FOURIER_DFTRC                32799
#define ID_FOURIER_FFT                  32800
#define ID_IDEAL_LOWPASS                32801
#define ID_IDEAL_HIGHPASS               32802
#define ID_GAUSSIAN_LOWPASS             32803
#define ID_GAUSSIAN_HIGHPASS            32804
#define ID_EDGE_ROBERTS                 32805
#define ID_EDGE_PREWITT                 32806
#define ID_EDGE_SOBEL                   32807
#define ID_HOUGH_LINE                   32808
#define ID_HARRIS_CORNER                32809
#define ID_COLOR_GRAYSCALE              32810
#define ID_COLOR_SPLIT_RGB              32811
#define ID_COLOR_SPLIT_HSI              32812
#define ID_COLOR_SPLIT_YUV              32813
#define ID_COLOR_COMBINE_RGB            32814
#define ID_COLOR_COMBINE_HSI            32815
#define ID_COLOR_COMBINE_YUV            32816
#define ID_COLOR_EDGE                   32817
#define ID_COLOR_EQUALIZE               32818
#define ID_SEGMENT_BINARIZATION         32819
#define ID_BINARIZATION_ITERATIVE       32820
#define ID_SEGMENT_LABELING             32821
#define ID_CONTOUR_TRACING              32822
#define ID_MORPHOLOGY_EROSION           32823
#define ID_MORPHOLOGY_DILATION          32824
#define ID_MORPHOLOGY_OPENING           32825
#define ID_MORPHOLOGY_CLOSING           32826
#define ID_GRAYMORPH_EROSION            32827
#define ID_GRAYMORPH_DILATION           32828
#define ID_GRAYMORPH_OPENING            32829
#define ID_GRAYMORPH_CLOSING            32830
#define ID_FOURIER_DESCRIPTOR           32831
#define ID_INVARIANT_MOMENTS            32832
#define ID_PLAY_PLAY                    32833
#define ID_PLAY_STOP                    32834
#define ID_PLAY_PAUSE                   32835
#define ID_PLAY_START                   32836
#define ID_PLAY_PREV                    32837
#define ID_PLAY_NEXT                    32838
#define ID_PLAY_END                     32839
#define ID_CAPTURE                      32840
#define ID_32841                        32841
#define ID_32842                        32842
#define ID_32843                        32843
#define ID_MODE_NORMAL                  32844
#define ID_MODE_DIFFERENCE              32845
#define ID_MODE_MOTION                  32846

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        148
#define _APS_NEXT_COMMAND_VALUE         32847
#define _APS_NEXT_CONTROL_VALUE         1052
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
